### ISSUE TITLE
[Bug] Error: [object Object] using AuthGuard with GraphQL

### ISSUE THREAD

**Issue by cdiaz** [nestjs/passport#5] opened 2018-05-06 22:32 UTC
When using the `AuthGuard` on a controller it works fine, but when used on a GraphQL query or mutation it shows the following error in terminal:

![alt text](https://i.imgur.com/4bdfP1C.png)

Probably graphql is waiting for the return of a false boolean in failure case, but authentication returns a http exception

[This is](https://github.com/cdiaz/nestjs-graphql-authguard) my example

**Comment by kamilmysliwiec** [comment] 2018-05-07 08:44
Duplicate of #4 🙂

**Comment by cdiaz** [comment] 2018-05-07 17:17
They are different bugs.
I've [updated](https://github.com/cdiaz/nestjs-graphql-authguard/blob/master/package.json#L17) to version 1.0.9 and this still persists

**Comment by kamilmysliwiec** [comment] 2018-05-07 19:16
Please, make sure to get rid of internal `@nestjs/common` package installed by `@nestjs/passport` (full path: node_modules/@nestjs/passport/node_modules/@nestjs/common)

**Comment by cdiaz** [comment] 2018-05-07 23:56
`node_modules/@nestjs/passport/node_modules/@nestjs/common` is not present, and still the error keeps appearing

![nestjs tree](https://0x0.st/sjZR.png)

**Comment by kamilmysliwiec** [comment] 2018-06-23 15:13
This isn't `AuthGuard` issue. I did a small research and it seems that this is how apollo serializes thrown error. If you throw "Test", it would print the following output:
```
Error: Test
```
Whilst `message` property of the `HttpException` is an object. Regardless of this weird console output, the GraphQL response looks perfectly fine:
![image](https://user-images.githubusercontent.com/23244943/41811058-ac47e42c-7708-11e8-91aa-0591c6ba928a.png)

**Closed by kamilmysliwiec** 2018-06-23 15:13 UTC
Labels: bug

**Comment by ph55** [comment] 2018-06-24 10:56
Okay.

But in general, if framework handled exception and proper response returned -
why it should be displayed in console ?

I mean, exception usually means something wrong happened in your application - and usually you want to crash it.

Don't you agree, @kamilmysliwiec ?

**Comment by ph55** [comment] 2018-06-24 12:05
I understand that.

But, you have power of suppressing such errors when wrapping it, don't you? Or am I wrong.
It's just question of design.

**Comment by kamilmysliwiec** [comment] 2018-06-24 12:07
@ph55, yeah, you have, using `formatError` option from Apollo. It has nothing to do with Nest.

**Comment by ph55** [comment] 2018-06-24 13:48
I don't think `formatError ` helps much.
I'll explain in another example.

User authentication service:
```ts
    const AuthenticationError = createError('AuthenticationError', {
      message: 'Username or password are incorrect'
    });

    if (!match) {
      throw new AuthenticationError();
    }
```

**Comment by ph55** [comment] 2018-06-24 13:53
I don't think `formatError ` helps much.
I'll explain in another example.

User authentication service:
```ts
    const AuthenticationError = createError('AuthenticationError', {
      message: 'Username or password are incorrect'
    });

    if (!match) {
      throw new AuthenticationError();
    }
```

Using format error gives me desired result in output:
```json
{
	"data": {
		"login": null
	},
	"errors": [
		{
			"message": "Username or password are incorrect",
			"name": "AuthenticationError",
			"time_thrown": "2018-06-24T13:47:39.214Z",
			"data": {}
		}
	]
}
```

But error **still thrown in console**:
```
[Nest] 4060   - 2018-6-24 16:47:37   [NestApplication] Nest application successfully started +30ms
AuthenticationError: Username or password are incorrect
    at UserService.<anonymous> (C:\Users\alex\Documents\_dev\nest-apps\src\@core\user\user.service.ts:51:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\alex\Documents\_dev\nest-apps\src\@core\user\user.service.ts:16:58)
    at <anonymous>
```

So the questions are:
1. Why its still thrown.
2. How to suppress it. 
3. Am I stupid ?

**Comment by cojack** [comment] 2019-01-12 19:04
Any progress?
